# Generated by Django 2.0.6 on 2018-06-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
