# Generated by Django 2.0.6 on 2018-06-28 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_product', '0006_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='from_email',
        ),
    ]
