# Generated by Django 2.0.6 on 2018-06-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_product', '0007_remove_email_from_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='from_email',
            field=models.EmailField(default='wilber.summitworks@gmail.com', max_length=254),
        ),
    ]
